services:
  patchef-client:
    build:
      context: .
      dockerfile: Dockerfile
    image: registry.kube.slc.net/slc/patchef-client
    container_name: patchef-client
    restart: always
    ports:
      - "6969:6969"
    env_file:
      - .env

networks:
  patchef-frontend-network:
    driver: bridge
