services:
  patchef-client:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: patchef-client
    image: DAFFODIL.ad.slc.net:5000/slc/patchef-client
    restart: always
    ports:
      - "3000:6969"
    env_file:
      - .env
