name: CI for PatChef Client

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build_and_push:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build Docker
        run: docker compose build
      - name: Push to Docker Registry
        run: docker compose push
